SET [ GLOBAL | SESSION ] TRANSACTION 
ISOLATION LEVEL [ SERIALIZABLE | REPEATABLE READ | READ COMMITTED | READ UNCOMMITTED ];

START TRANSACTION;
SELECT * FROM Employee;
DELETE FROM Employee WHERE Name = 'Lisa Ellison';
SAVEPOINT First;
SELECT * FROM Employee;
SELECT * FROM Employee;
DELETE FROM Employee WHERE Name = 'Sam Snead';
DELETE FROM Employee WHERE Name = 'Jiho Chen';
SAVEPOINT Second;
SELECT * FROM Employee;
ROLLBACK TO First;
COMMIT;